# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2024.32-11-ge1d24e2
_src_path: .
admin_email: admin@example.com
author_email: jdoe@example.com
author_name: John Doe
current_version: 2024.7.1
default_from_email: johndoe@example.com
django_version: '5.0'
docs_site_name: With_Vite
domain_name: with_vite.westervelt.com
fly_app_name: with_vite-example_owner
fly_primary_region: atl
github_owner: example_owner
github_repo: with_vite
include_vite: true
include_weasyprint: false
module_name: with_vite
node_version: '20'
playwright_version: 1.45.0
postgres_docker_image: postgres
postgres_docker_version: '15'
project_name: with_vite
python_version: '3.12'
sentry_dsn: https://example.com
sentry_org: the-westervelt-company
sentry_project: with_vite
tailwindcss_version: 3.4.6
use_r2: false
