# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1e5c730
_src_path: .
admin_email: admin@example.com
author_name: John Doe
current_version: 2024.4.1
default_from_email: johndoe@example.com
django_version: '4.2'
domain_name: with_vite.westervelt.com
fly_app_name: with_vite-example_owner
fly_primary_region: atl
github_owner: example_owner
github_repo: with_vite
include_vite: true
include_weasyprint: false
module_name: with_vite
node_version: '20'
op_vault: with_vite
postgres_docker_image: postgres
postgres_docker_version: '15'
project_name: with_vite
python_version: '3.12'
sentry_dsn: https://example.com
sentry_org: the-westervelt-company
sentry_project: with_vite
tailwindcss_version: 3.4.0
