version: "3"

x-app: &prod-app
  build:
    target: final
  environment:
    DEBUG: False
    ENABLE_SENTRY: ${ENABLE_SENTRY:-False}

x-no-run: &no-run
  profiles:
    - not-prod

services:
  app:
    <<: *prod-app

  tailwind:
    <<: *no-run

  worker:
    <<: *prod-app
