# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2024.36-7-gd302c2e
_src_path: .
admin_email: admin@example.com
author_email: jdoe@example.com
author_name: John Doe
current_version: 2024.8.1
default_from_email: johndoe@example.com
django_twc_ui_version: 2024.7.29
django_version: '5.0'
docs_site_name: Default
domain_name: default.westervelt.com
fly_app_name: default-example_owner
fly_primary_region: atl
github_owner: example_owner
github_repo: default
include_vite: false
include_weasyprint: false
module_name: default
node_version: '20'
playwright_version: 1.45.0
postgres_docker_image: postgres
postgres_docker_version: '15'
project_name: default
python_version: '3.12'
sentry_dsn: https://example.com
sentry_org: the-westervelt-company
sentry_project: default
tailwindcss_version: 3.4.6
use_r2: false
